# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the Project
      - name: Build Project
        run: npm run build

      # 5. Add CNAME File
      - name: Add CNAME to dist
        run: echo "fatihmutlu.com" > ./dist/CNAME

      # 6. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # 7. Upload Artifact to GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # 8. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
