# Install Node.js
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18 # Use the version of Node.js that matches your project requirements

  # Install dependencies and build the project
  - name: Install dependencies
    run: npm install
  - name: Build project
    run: npm run build

  # Setup Pages and upload the built artifact
  - name: Setup Pages
    uses: actions/configure-pages@v5

  - name: Prepare dist
    run: |
      echo "customdomain.com" > ./dist/CNAME
      echo "www.customdomain.com" > ./dist/CNAME
  - name: Copy CNAME
    run: cp CNAME ./dist/
      
  - name: Upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: './dist'


  # Deploy to GitHub Pages
  - name: Deploy to GitHub Pages
    id: deployment
    uses: actions/deploy-pages@v4
